### ISSUE TITLE
Nestjs build perfomance issue when using node-config 

### ISSUE THREAD

**Issue by lavagri** [node-config/node-config#613] opened 2020-07-12 19:13 UTC
### I'm submitting a ... 
  - [x] bug report
  - [  ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the current behavior?
Hi guys, I'm faced with typescript build perfomance issue while using node-config. I have middle-size monolithic application on Nestjs. Build time was increase dramatically when I'm starting to use node-config in probably each component files. For now, `nest start` take about 45-65 seconds on my laptop. But after removing all `config` imports it takes 1.5-2sec as expected. Thats hard to say whats wrong...I was catch that `util.getCustomEnvVars` takes too much time, maybe this should be new start point in investigation in future.

To easy reproduce, I created [public repo here](https://github.com/vladLazurenko/nestjs-config-test) - forked from Nest js starter kit project. Hope it will helps! Here build time could be from 4 to 12s depends on machine, but if you checkout to `test/no-config` - you will see build time difference.
By the way, `TS_NODE_TRANSPILE_ONLY=true` flag helps me to decrease build time in 2-3 times, but it still too much and I want not to use this flag anyway. 

### What is the expected behavior?
I expect for node-config package to not add to the build time for more than ~1 second.

### Please tell us about your environment:

 -  node-config version: ^3.3.1
 -  typescript: ^3.9.3
 -  node-version: 12.16.1
 
### Other information
Please also take a look to test repo description.

Thank you for your attention!

**Comment by Dunnodv** [comment] 2020-07-21 13:34
Had the same problem. 
One of the possible solutions is using ***.js** as configuration files instead of ***.ts**

**Comment by dsbert** [comment] 2020-10-26 13:31
I am also using a Nestjs app and have not noticed this issue using `.yaml` configuration files

**Comment by markstos** [comment] 2021-10-06 12:15
FYI @flodaniel

**Comment by ghm-salvarado** [comment] 2022-02-08 23:14
Similar issue here but with Next.js — TTFB on the initial page load is very slow but gets reduced by 68% on average by using non-typescript config files as suggested above. However in my case, typed config is a requirement, so I put a workaround in place as shown here:

`generate-config.js`
```js
const fs = require('fs')
const config = require('config')

fs.writeFileSync(
  'app-config.json',
  JSON.stringify(config.util.toObject())
)
```

---

`app-config.d.ts`
```ts
import { AppConfig } from './types/config'

declare module 'app-config' {
  const config: AppConfig
  export = config
}
```

---

`.gitignore`
```
app-config.json
```

---

`package.json`
```json
{
  "scripts": {
    "prebuild": "node generate-config.js",
    "predev": "node generate-config.js",
  }
}
```

---

_usage_
```ts
import config from './app-config.json' // properly typed due to app-config.d.ts above
console.log(config.foo.bar)
```

You could also `Object.freeze(config)` if you want to make sure it's immutable. It's not an ideal solution but works if you only use the basic `config.get()` functionality.

**Comment by markstos** [comment] 2022-02-15 03:24
The maintainers are not using `node-config` in combination with Nest.js or Next.js. If are you are impacted user, consider looking into the root cause.

**Comment by markstos** [comment] 2022-02-15 14:19
I think the comment above may be on to something: the `.ts` config files that are the cause. Trying `.js` config files may help. It's not clear how much typing is helping in config files anyway.

https://github.com/node-config/node-config/issues/613#issuecomment-661865084

If you want to type and validate a complex set of config files, you might try something like the CUE lang, which could then generate JSON files which `node-config` would consume:

https://cuelang.org/

**Comment by markstos** [comment] 2023-08-04 02:32
Closing because #721 was merged.

**Closed by markstos** 2023-08-04 02:32 UTC
Labels: pr-welcome, collab-request
