### ISSUE TITLE
[BUG] config.get('variable') can not read from custom-environment-variables

### ISSUE THREAD

**Issue by MahmonirB** [node-config/node-config#714] opened 2023-01-06 14:44 UTC
### **What is the Problem?**

When I set up config folder with: development.json, default.json, production.json and custom-environment-variables.json, variables that are defined as > export dbUrl="xxx" into process environment, can not be read when I want to use it as `config.get('dbUrl')`.

I try it either to set it into each json file or just into custom-environment-variables.json file, but in both it can not read from `config.get('dbUrl')`.

### **Versions:**
 -  config: "^3.3.8",
 -  node-version: v16.13.1
 
 I checked name of `custom-environment-variables.json` some times, It's correct but it can not read from it, Also when I used process.env.dbUrl it's ok and I can access to the variable. How should I do that is missed?

**Comment by talhameer** [comment] 2023-02-21 12:51
I'm also facing the same issue when using ES modules `import` in JS and TS as well. Following is the error what I receive in the console.
```shell
D:\TechACOS\dar-app\dar-api\node_modules\config\lib\config.js:179
    throw new Error('Configuration property "' + property + '" is not defined');
          ^
Error: Configuration property "dar-api-port" is not defined
```

**Comment by markstos** [comment] 2023-02-28 18:59
Please contribute a failing test for the test suite that demonstrates the bug.  This feature is working fine for me. The test will help illustrate what's different in your case.

**Comment by devtrix** [comment] 2023-03-10 00:08
I have the same issue in my node app.  I am not sure what test suite to use etc, apologize for my ignorance.  But here is what I have.  I have default.json, development.json and production.json.  I have an environment variable 'app_password' with password. I have custom-environment-variables.json with the following:
`
{
    "mail":{
            "password":"app_password"
        }
}

`
In my index.js I have 
`console.log('Mail Password: ' + config.get('mail.password'));`
I get the following error
Error: Configuration property "mail.password" is not defined
    at Config.get (C:\Users\devtr\Desktop\Vidly\node_modules\config\lib\config.js:179:11)
etc etc.

I hope this helps and can get it resolved.  Thank you

**Comment by talhameer** [comment] 2023-03-10 05:25
@devtrix how are you importing the config module in your code?

**Comment by devtrix** [comment] 2023-03-10 06:19
@talhameer The second, const config = require("config")

**Comment by MahmonirB** [comment] 2023-03-13 20:58
When I define a variable that is set into 'custom-environment-variables.json'  but not set into development.json, I got error that is not found:

```
└───────────────────────────────────┘
Config { name: 'My app - development', jwtPrivateKey: '' }
/..../GitHub/nodejs-starter/startup/config.js:6
        throw new Error("FATAL ERROR: jwt key not found!");
```

Here is my config.js file:
```
const config = require("config");

module.exports = function() {
    if (!config.get("jwtPrivateKey")) {
        throw new Error("FATAL ERROR: jwt key not found!"); 
        return process.exit(1);
      }      
}
```

This is my development.json:
```
{
    "name": "My app - development",
    "jwtPrivateKey": ""
}
```

And into `custom-environment-variables.json` file, I have just this field `jwtPrivateKey`.
There are other json files into config folder, production and default that are same as development but with different name.

That's interesting that some months ago when I was working with these config files, it worked well.

**Comment by reddythedev** [comment] 2023-04-28 18:26
I'm getting this error too.

**Comment by elqessouartariq** [comment] 2023-05-01 02:23
I am encountering the same error when I run the server in VS Code's integrated terminal, but when I run it in an external terminal, it works without any issues.

**Comment by markstos** [comment] 2023-05-01 13:42
Everyone, you need to confirm that the environment variable you are trying to read is actually passed to `node-config`. 

In the first line in your script, use something like `console.log("DEBUG", process.env.YOUR_VAR_NAME)`. If you don't get any output, the variable is not set by your environment and there's nothing `node-config` can do about that.

I'm closing this thread, because it's more of a support thread and not a bug report-- If there was an actual bug, you could contribute a failing test for the test suite to reproduce it as something that's definitely a node-config problem.

**Closed by markstos** 2023-05-01 13:42 UTC
Labels: pending-more-information

**Comment by seAfnan** [comment] 2023-05-17 17:42
The issue is with VS Code Terminal. It not picking the file or object.
Try external node terminal. It will work.
