### ISSUE TITLE
[BUG] Extra quotes on config file broke app

### ISSUE THREAD

**Issue by Eddcp** [node-config/node-config#739] opened 2023-08-03 17:29 UTC
**Describe the bug**
We use Vault (Hashicorp) for reading secrets and since a recent update our lib added an extra quote `"` on values ... And that shouldn't break applications. 

We have other microservices that read the `secrets.env` file directly and they haven't broken. This other service that uses `config` to set up our database host, password, user, etc. ended up being broken.

We're using Knex to do database operations. Perhaps this should be an issue for them to verify (Close this issue if you find it's not suitable)

**Expected behavior**
Perhaps the config package should be clever enough to check these " and ignore them.

### Please tell us about your environment:

 -  node-config version: 3.3.8
 -  node-version: node:16-alpine Docker image

**Comment by lorenwest** [comment] 2023-08-03 17:33
A little unclear as to the file containing an extra quote.  Is it a YAML file, a JSON file, or... and is it valid JSON/YAML/etc?  Node-config uses off the shelf parsers, so if it won't parse a file it's likely due to an invalid format (maybe needing an escape before the quote).

It would help if you attach the file, or an example of a file that has problems.

**Comment by lorenwest** [comment] 2023-08-03 18:04
Node-config uses the npm ```properties``` package for parsing .properties files.  Maybe open a support ticket on that module, or get more clarity on valid ```.properties``` file format.

https://github.com/gagle/node-properties

**Comment by markstos** [comment] 2023-08-03 21:30
@Eddcp Try parsing your  `.properties` file directly with the `properties` package to confirm if the bug is in that package or not.

**Comment by markstos** [comment] 2023-08-04 02:15
I'm closing this as it appears to be a bug with the properties module. Comment to re-open if it's a confirmed bug with node-config instead.

**Closed by markstos** 2023-08-04 02:15 UTC
