### ISSUE TITLE
custom-environment-variables.json says variable is not defined.

### ISSUE THREAD

**Issue by devtrix** [node-config/node-config#725] opened 2023-03-10 07:17 UTC
I had this as a comment in issue#714 but moved it here.
OS: Windows 11
Node ver: 18.13.0
Config: 3.3.9

Importing like this: const config = require('config');

Here is what I have. I have default.json, development.json and production.json. I have an environment variable 'app_password' with password. I have custom-environment-variables.json with the following:

`
{
"mail":{
"password":"app_password"
}
}

`
In my index.js I have

`
console.log('Mail Password: ' + config.get('mail.password'));

`
I get the following error
Error: Configuration property "mail.password" is not defined
at Config.get (C:\Users\devtr\Desktop\Vidly\node_modules\config\lib\config.js:179:11)
etc etc.

NOTE:  This only happens when I tried to read from the Windows Environment, however when the key/value is added to .env file it works just fine.

I hope this helps and can get it resolved. Thank you

**Comment by markstos** [comment] 2023-05-01 13:44
Closing as dupe of #714

**Closed by markstos** 2023-05-01 13:44 UTC
