### ISSUE TITLE
Use with react native Metro bundler

### ISSUE THREAD

**Issue by rendomnet** [node-config/node-config#547] opened 2019-04-05 03:05 UTC
### I'm submitting a ... 
  - [  ] bug report
  - [ x ] feature request
  - [  ] support request or question => Please do not submit support request or questions here, see note at the top of this template.

### What is the expected behavior?
Can we use Metro bundler and node-config to store our config to global variable on bundling stage? Is it possible?

### Please tell us about your environment:

 -  node-config version: 0.0.2
 -  node-version: 8.12.0
 
### Other information

(e.g. are you using an environment besides Node.js?)

**Comment by markstos** [comment] 2019-04-05 19:54
Is this a dupe of number #367, a request for React Native support?

**Comment by markstos** [comment] 2022-09-27 18:39
Closing as possible dupe, stale, lack of interest.

**Closed by markstos** 2022-09-27 18:39 UTC
